FROM dbrain/base:gpu

RUN git clone --recursive https://github.com/Microsoft/LightGBM \
	&& cd LightGBM \
	&& git checkout tags/v2.1.2 \
	&& mkdir build \
	&& cd build \
	&& cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include/ ..\
	&& make -j4 \
	&& cd ../python-package \
	&& python setup.py install --precompile \
	&& cd ../.. \
	&& rm -rf LightGBM
