FROM dbrain/base:gpu

RUN git clone --recursive https://github.com/dmlc/xgboost \
	&& cd xgboost \
	&& git checkout tags/v0.80 \
	&& mkdir build \
	&& cd build \
	&& cmake .. -DUSE_CUDA=ON \
	&& make -j4 \
	&& cd ../python-package \
	&& python setup.py install \
	&& cd ../.. \
	&& rm -rf xgboost
