FROM dbrain/base:gpu
RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         vim \
         ca-certificates \
         libjpeg-dev \
         libpng-dev \ 
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install http://download.pytorch.org/whl/cu91/torch-0.4.0-cp36-cp36m-linux_x86_64.whl torchvision tensorboardX
